name: Movimento dos Trabalhadores Rurais Sem Terra
markdown: redcarpet
pygments: true
exclude: [deploy, Gemfile, Gemfile.lock, Gruntfile.js, README.md, bower.json, drupal_queries.sql, jekyll_mst.rb, node_modules, package.json]
baseurl: /site-novo
# permalink: /:categories/:title
pages: ./_pages
# paginate: 25
# paginate_path: "page:num"
