name: Movimento dos Trabalhadores Rurais Sem Terra
markdown: redcarpet
pygments: true
exclude:
  - deploy
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - README.md
  - bower_components
  - bower.json
  - drupal_queries.sql
  - jekyll_mst.rb
  - node_modules
  - package.json
  - vendor
  - assets/less
pages: ./_pages

